name: appui
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  firebase_auth:

dev_dependencies:
  flutter_test:
    sdk: flutter
    

flutter:

  uses-material-design: true
  assets:
   - assets/propic.jpg
   - assets/spend/1.png
   - assets/spend/2.png
   - assets/spend/3.png
   - assets/spend/4.png
   - assets/bottomnav/1.png
   - assets/bottomnav/2.png
   - assets/bottomnav/3.png
   - assets/bottomnav/4.png
